---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
co2_df <- read_csv('../ShinyClimate/data/co2_cleaned.csv')
```

```{r}
country = "United States"
co2_df |> filter(Country == country & CTS_Code == "ECNGDE" & Gas_Type == "Greenhouse gas")
```
```{r}
country = "United States"
y1 = 1990
y2= 2018
years <- as.numeric(substring(names(co2_df)[7:ncol(co2_df)], 2))
row1 <- co2_df |> filter(Country == country & CTS_Code == "ECNGDE" & Gas_Type == "Greenhouse gas")
ghg_values <- as.numeric(row1[1, 7:ncol(co2_df)])/1000
row2 <- co2_df |> filter(Country == country & Industry == "Energy" & Gas_Type == "Carbon dioxide")
co2_values <- as.numeric(row2[1, 7:ncol(co2_df)])/1000

# Create data frames for each type
ghg_data <- data.frame(years = years, values = ghg_values, type = rep("Total", length(ghg_values)))
co2_data <- data.frame(years = years, values = co2_values, type = rep("CO2", length(co2_values)))

# Combine data for plotting
plot_data <- rbind(ghg_data, co2_data)

# Plotting
plot_data |>
  filter(years >= y1 & years <= y2) |>
  ggplot(aes(x = years, y = values, color = type)) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  labs(title = paste("Emissions from 1970 to 2021 for", country),
       x = "Years",
       y = "Giga-tons of CO2 equivalent") +
  theme_minimal()

```
```{r}
ghg <-co2_df |> 
  filter(ISO2 != "ZZ" & CTS_Code == "ECNGDE" & Gas_Type == "Greenhouse gas") |>
  arrange(desc(F1970)) |> 
  slice(1:5) 
```




```{r}
co2_df |> 
  filter(ISO2 != "ZZ" & CTS_Code == "ECNGDE" & Gas_Type == "Greenhouse gas") |>
  arrange(desc(F1970)) |> 
  slice(1:5) |>
  ggplot(aes(x = reorder(Country, -F1970), y = F1970)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "Top 10 GH gas Emitters",
       x = "F1970",
       y = "Country")
```

