---
title: "temperature"
output: html_document
date: "2024-01-19"
---

```{r}
library(tidyverse)
```

```{r}
temps <- read_csv('../ShinyClimate/data/temperature.csv')
```

```{r}
temps |>
ggplot(aes(x = Year, y = World, fill = World)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "blue", high = "red") +  # Adjust the color scale
  labs(x = "Year", y = "Value", title = "Mean Temperature Change") +
  theme_classic()
```

```{r}
anomalies <- read_csv('../ShinyClimate/data/LandOceanTemperatureIndex.csv')
anomalies |> ggplot(aes(x = Year)) +
  geom_line(aes(y = No_smoothing), color = "blue", linetype = "solid") +
  geom_point(aes(y = No_smoothing), color = "blue", size = 2) +
  geom_line(aes(y = Lowess), color = "red", linetype = "solid") +
  labs(x = "Year", y = "Values") +
  theme_classic()
```


```{r}
temps$World[temps$Year == 2021]
```

```{r}
    which_sea <- "World"
    sealevels |> 
      filter(Ocean == which_sea) |>
      ggplot(aes(x = Decimal_Date, y = Value, color = Value)) +
      geom_line() +
      scale_color_gradient(low = "blue", high = "red") +  # Adjust the color scale
      labs(x = "Year", y = "Value", title = paste("Mean Sea Level:",which_sea)) +
      theme_classic()
```

```{r}
sealevels <- read_csv('../ShinyClimate/data/Change_in_Mean_Sea_Levels.csv')
which_sea <- "World"

df <- sealevels

colors <- c('TOPEX' = 'red',
            'Jason.1' = 'blue',
            'Jason.2' = 'green',
            'Jason.3' = 'yellow')

# Create an empty ggplot object
sealevels |> 
      filter(Ocean == which_sea) |>
ggplot(aes(x = Decimal_Date, y = Value, color = Satellite)) +
  geom_line() +
  labs(title = 'Decimal_Date vs Value', x = 'Decimal_Date', y = 'Value') +
  scale_color_manual(values = colors)

```
```{r}
sealevels |>
  filter(Ocean == "World" & Decimal_Date>2022)
```

```{r}
mean_sealevel_trends <- read_csv('data/Mean_Sea_Levels_Trends.csv')
world_sealevel_trend <- mean_sealevel_trends|>
  filter(Ocean == 'World') |>
  pull(Value)
mean_sealevel_trends |>
    filter(Ocean != 'World') |>
ggplot(aes(x = Value, y = reorder(Ocean, Value))) +
  geom_bar(stat = "identity", fill = "green", color = "white") +
  labs(title = "Trends in Mean Sea Levels",
       x = "Mean yearly change in sea level (mm)",
       y = "") +
  theme_classic() +
  geom_vline(xintercept = 3.02, linetype = "dashed", color = "red") +
  annotate("text", x = 3.02, y = Inf, vjust = 1.5, hjust = -.2, label = "World", color = "red", hjust = 0)
```
```{r}
mean_sealevel_trends|>
  filter(Ocean == 'World') |>
  pull(Value)
```



```{r}
oceans <- sealevels|>
  pull(Ocean)  |>
  unique()

major_oceans <- c("World", "Pacific Ocean", "Atlantic Ocean", "Indian Ocean")
  oceans <- setdiff(oceans, major_oceans)

# Add them to the beginning of the array
oceans <- c(major_oceans, oceans)
```

```{r}
gmsl_hist <- read_csv('data/CSIRO_Recons_gmsl_yr_2015.csv')

    gmsl_hist |>
      ggplot(aes(x = Time, y = GMSL)) +
      geom_line(color = "blue") +  # Set plot color to blue
      geom_ribbon(aes(ymin = GMSL - GMSL_unc, ymax = GMSL + GMSL_unc), fill = "green", alpha = 0.3) +  # Set ribbon color to light blue
      labs(title = "Global Sea Levels (Tide gauge data)", x = "Year", y = "Global Mean Sea Level (mm)") +
      theme_classic()
```

